export const ACTIVITIES_SYNC_START = 'ACTIVITIES_SYNC_START'
export const ACTIVITIES_SYNC_STATE = 'ACTIVITIES_SYNC_STATE'
export const ACTIVITIES_PAGE_LOADING_COMPLETE = 'ACTIVITIES_PAGE_LOADING_COMPLETE'
