export const STRAVA_AUTH_START = 'STRAVA_AUTH_START'
export const STRAVA_AUTH_TOKEN_VALIDATE = 'STRAVA_AUTH_TOKEN_VALIDATE'
export const STRAVA_AUTH_TOKEN_UPDATE = 'STRAVA_AUTH_TOKEN_UPDATE'
export const STRAVA_AUTH_LOG_OUT = 'STRAVA_AUTH_LOG_OUT'
